services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"    
    volumes:
      - mongo-data:/data/db  # Volumen para persistir los datos de MongoDB

volumes:
  mongo-data:
    driver: local
